# Generated by Django 5.2.6 on 2025-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtinnhanvien',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CCCD/CMND'),
        ),
    ]
