# Generated by Django 5.2.6 on 2025-10-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_thongtinnhanvien_cccd'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonXinNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_ngay', models.DateField()),
                ('den_ngay', models.DateField()),
                ('loai_nghi', models.CharField(choices=[('nghi_phep', 'Nghỉ phép'), ('nghi_om', 'Nghỉ ốm'), ('nghi_co_phep', 'Nghỉ có phép'), ('nghi_khong_phep', 'Nghỉ không phép')], default='nghi_phep', max_length=20)),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('ly_do_tu_choi', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('ngay_xoa', models.DateTimeField(blank=True, null=True)),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_duyet', to='barbershop.nguoidung')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_xin_nghi', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Đơn xin nghỉ',
                'verbose_name_plural': 'Đơn xin nghỉ',
                'db_table': 'don_xin_nghi',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
