# Generated by Django 5.2.6 on 2025-10-04 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_donxinnghi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], help_text='Đánh giá từ 1-5 sao')),
                ('noi_dung', models.TextField(help_text='Nội dung đánh giá của khách hàng')),
                ('hinh_anh', models.ImageField(blank=True, help_text='Hình ảnh đính kèm (tùy chọn)', null=True, upload_to='reviews/')),
                ('phan_hoi', models.TextField(blank=True, help_text='Phản hồi từ quản lý', null=True)),
                ('ngay_phan_hoi', models.DateTimeField(blank=True, null=True)),
                ('da_duyet', models.BooleanField(default=True, help_text='Đánh giá đã được duyệt hiển thị')),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('ngay_xoa', models.DateTimeField(blank=True, null=True)),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_dich_vu', to='barbershop.dichvu')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_hoa_don', to='barbershop.hoadon')),
                ('khach_hang', models.ForeignKey(limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_khach_hang', to='barbershop.nguoidung')),
                ('nguoi_phan_hoi', models.ForeignKey(blank=True, limit_choices_to={'vai_tro': 'quan_ly'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phan_hoi_danh_gia', to='barbershop.nguoidung')),
                ('nhan_vien', models.ForeignKey(limit_choices_to={'vai_tro': 'nhan_vien'}, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_nhan_vien', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'danh_gia',
                'ordering': ['-ngay_tao'],
                'unique_together': {('khach_hang', 'hoa_don', 'dich_vu')},
            },
        ),
    ]
