# Generated by Django 5.2.6 on 2025-10-04 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_danhgia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caidathethong',
            name='gia_tri',
        ),
        migrations.RemoveField(
            model_name='caidathethong',
            name='khoa',
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='che_do_bao_tri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='che_do_toi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='cho_phep_chon_nhan_vien',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='da_xoa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='dia_chi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='email_bao_cao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='email_hoa_don',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='gio_dong_cua',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='gio_mo_cua',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='gui_nhac_nho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='hotline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='lan_sao_luu_cuoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='loai_dat_coc',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('%', '%')], default='VND', max_length=10),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='mau_chu_dao',
            field=models.CharField(default='#8b4513', max_length=7),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='mau_phu',
            field=models.CharField(default='#d2691e', max_length=7),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='ngay_lam_viec',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='sms_dat_lich_moi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='sms_huy_lich',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='sms_nhac_lich_hen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='so_dien_thoai_momo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='so_tai_khoan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='so_tien_dat_coc',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='ten_ngan_hang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='ten_tiem',
            field=models.CharField(default='Barbershop HotTocNam', max_length=200),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thanh_toan_chuyen_khoan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thanh_toan_momo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thanh_toan_the',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thanh_toan_tien_mat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thanh_toan_vnpay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thoi_gian_dat_truoc_toi_da',
            field=models.IntegerField(default=43200),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thoi_gian_dat_truoc_toi_thieu',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thoi_gian_huy_lich',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='thoi_gian_slot',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='tu_dong_sao_luu',
            field=models.CharField(choices=[('none', 'Không tự động'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='tu_dong_xac_nhan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='vnpay_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caidathethong',
            name='yeu_cau_dat_coc',
            field=models.BooleanField(default=False),
        ),
    ]
