# Generated by Django 5.2.6 on 2025-10-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_update_settings_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lam', models.DateField()),
                ('gio_vao', models.TimeField(blank=True, null=True)),
                ('gio_ra', models.TimeField(blank=True, null=True)),
                ('gio_vao_chuan', models.TimeField(default='08:00')),
                ('gio_ra_chuan', models.TimeField(default='17:00')),
                ('tong_gio_lam', models.DurationField(blank=True, null=True)),
                ('gio_lam_them', models.DurationField(blank=True, null=True)),
                ('trang_thai_vao', models.CharField(choices=[('dung_gio', 'Đúng giờ'), ('tre', 'Trễ'), ('som', 'Sớm'), ('vang_mat', 'Vắng mặt')], default='dung_gio', max_length=20)),
                ('trang_thai_ra', models.CharField(choices=[('dung_gio', 'Đúng giờ'), ('tre', 'Trễ'), ('som', 'Sớm'), ('vang_mat', 'Vắng mặt')], default='dung_gio', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cham_cong', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'db_table': 'cham_cong',
                'ordering': ['-ngay_lam', 'nhan_vien__ho_ten'],
                'unique_together': {('nhan_vien', 'ngay_lam')},
            },
        ),
    ]
