# Generated by Django 5.2.6 on 2025-10-06 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0006_chamcong'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('thu_tu', models.IntegerField(default=0)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'db_table': 'danh_muc_san_pham',
                'ordering': ['thu_tu', 'ten_danh_muc'],
            },
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('nha_cung_cap', models.CharField(max_length=200)),
                ('ngay_nhap', models.DateTimeField(default=django.utils.timezone.now)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('da_nhap_kho', 'Đã nhập kho'), ('huy', 'Hủy')], default='cho_duyet', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('nhan_vien_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_nhap_kho', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'db_table': 'phieu_nhap_kho',
                'ordering': ['-ngay_nhap'],
            },
        ),
        migrations.CreateModel(
            name='PhieuXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=50, unique=True)),
                ('loai_xuat', models.CharField(choices=[('ban_hang', 'Bán hàng'), ('su_dung_dich_vu', 'Sử dụng dịch vụ'), ('hao_hut', 'Hao hụt'), ('tra_hang', 'Trả hàng'), ('khac', 'Khác')], default='su_dung_dich_vu', max_length=20)),
                ('ngay_xuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('ly_do', models.CharField(max_length=200)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('da_xuat_kho', 'Đã xuất kho'), ('huy', 'Hủy')], default='cho_duyet', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('nhan_vien_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_xuat_kho', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'db_table': 'phieu_xuat_kho',
                'ordering': ['-ngay_xuat'],
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=50, unique=True)),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('loai_san_pham', models.CharField(choices=[('dung_cu', 'Dụng cụ'), ('san_pham', 'Sản phẩm chăm sóc'), ('nguyen_lieu', 'Nguyên liệu'), ('khac', 'Khác')], default='san_pham', max_length=20)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('don_vi_tinh', models.CharField(default='cái', max_length=20)),
                ('gia_nhap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gia_ban', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('so_luong_ton_kho', models.IntegerField(default=0)),
                ('so_luong_toi_thieu', models.IntegerField(default=0)),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai', models.CharField(choices=[('con_hang', 'Còn hàng'), ('sap_het', 'Sắp hết'), ('het_hang', 'Hết hàng'), ('ngung_kinh_doanh', 'Ngừng kinh doanh')], default='con_hang', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='barbershop.danhmucsanpham')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'san_pham',
                'ordering': ['ten_san_pham'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia_xuat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='barbershop.phieuxuatkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_xuat', to='barbershop.sanpham')),
            ],
            options={
                'verbose_name': 'Chi tiết xuất kho',
                'verbose_name_plural': 'Chi tiết xuất kho',
                'db_table': 'chi_tiet_xuat_kho',
            },
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia_nhap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('han_su_dung', models.DateField(blank=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='barbershop.phieunhapkho')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_nhap', to='barbershop.sanpham')),
            ],
            options={
                'verbose_name': 'Chi tiết nhập kho',
                'verbose_name_plural': 'Chi tiết nhập kho',
                'db_table': 'chi_tiet_nhap_kho',
            },
        ),
    ]
