# Generated by Django 5.2.6 on 2025-10-11 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0007_danhmucsanpham_phieunhapkho_phieuxuatkho_sanpham_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuaTangDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_qua', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('diem_yeu_cau', models.IntegerField(help_text='Số điểm cần để đổi quà')),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('so_luong_con_lai', models.IntegerField(default=0)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('da_xoa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quà tặng điểm',
                'verbose_name_plural': 'Quà tặng điểm',
                'db_table': 'qua_tang_diem',
                'ordering': ['diem_yeu_cau'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='chuyen_nghiep',
            field=models.BooleanField(default=False, verbose_name='Chuyên nghiệp'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='danh_gia_stylist',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, help_text='Đánh giá thợ cắt từ 1-5 sao'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='dat_lich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_dat_lich', to='barbershop.datlich'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='dung_gio',
            field=models.BooleanField(default=False, verbose_name='Đúng giờ'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='sach_se',
            field=models.BooleanField(default=False, verbose_name='Sạch sẽ'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='than_thien',
            field=models.BooleanField(default=False, verbose_name='Thân thiện'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='dich_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_dich_vu', to='barbershop.dichvu'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='hinh_anh',
            field=models.TextField(blank=True, help_text='JSON array of image paths', null=True),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='hoa_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_hoa_don', to='barbershop.hoadon'),
        ),
        migrations.AlterField(
            model_name='danhgia',
            name='so_sao',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], help_text='Đánh giá tổng thể từ 1-5 sao'),
        ),
        migrations.CreateModel(
            name='GiaoDichDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giao_dich', models.CharField(choices=[('cong', 'Cộng điểm'), ('tru', 'Trừ điểm')], max_length=10)),
                ('so_diem', models.IntegerField()),
                ('mo_ta', models.TextField()),
                ('diem_truoc', models.IntegerField(default=0)),
                ('diem_sau', models.IntegerField(default=0)),
                ('ngay_giao_dich', models.DateTimeField(default=django.utils.timezone.now)),
                ('hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich_diem', to='barbershop.hoadon')),
                ('khach_hang', models.ForeignKey(limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='giao_dich_diem', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Giao dịch điểm',
                'verbose_name_plural': 'Giao dịch điểm',
                'db_table': 'giao_dich_diem',
                'ordering': ['-ngay_giao_dich'],
            },
        ),
        migrations.CreateModel(
            name='LichSuDoiQua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_diem_da_dung', models.IntegerField()),
                ('ngay_doi', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_chuan_bi', 'Đang chuẩn bị'), ('da_giao', 'Đã giao'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('khach_hang', models.ForeignKey(limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doi_qua', to='barbershop.nguoidung')),
                ('qua_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_doi', to='barbershop.quatangdiem')),
            ],
            options={
                'verbose_name': 'Lịch sử đổi quà',
                'verbose_name_plural': 'Lịch sử đổi quà',
                'db_table': 'lich_su_doi_qua',
                'ordering': ['-ngay_doi'],
            },
        ),
        migrations.CreateModel(
            name='VoucherKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhan', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngay_su_dung', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('chua_su_dung', 'Chưa sử dụng'), ('da_su_dung', 'Đã sử dụng'), ('het_han', 'Hết hạn')], default='chua_su_dung', max_length=20)),
                ('hoa_don_su_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_su_dung', to='barbershop.hoadon')),
                ('khach_hang', models.ForeignKey(limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_cua_toi', to='barbershop.nguoidung')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duoc_su_dung_boi', to='barbershop.voucher')),
            ],
            options={
                'verbose_name': 'Voucher khách hàng',
                'verbose_name_plural': 'Voucher khách hàng',
                'db_table': 'voucher_khach_hang',
                'ordering': ['-ngay_nhan'],
            },
        ),
        migrations.CreateModel(
            name='StylistYeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_them', models.DateTimeField(default=django.utils.timezone.now)),
                ('khach_hang', models.ForeignKey(limit_choices_to={'vai_tro': 'khach_hang'}, on_delete=django.db.models.deletion.CASCADE, related_name='stylists_yeu_thich', to='barbershop.nguoidung')),
                ('stylist', models.ForeignKey(limit_choices_to={'vai_tro': 'nhan_vien'}, on_delete=django.db.models.deletion.CASCADE, related_name='duoc_yeu_thich_boi', to='barbershop.nguoidung')),
            ],
            options={
                'verbose_name': 'Stylist yêu thích',
                'verbose_name_plural': 'Stylist yêu thích',
                'db_table': 'stylist_yeu_thich',
                'ordering': ['-ngay_them'],
                'unique_together': {('khach_hang', 'stylist')},
            },
        ),
    ]
