# Generated by Django 5.2.6 on 2025-10-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0008_quatangdiem_alter_danhgia_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietxuatkho',
            name='phieu_xuat',
        ),
        migrations.RemoveField(
            model_name='chitietxuatkho',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='danh_muc',
        ),
        migrations.RemoveField(
            model_name='phieunhapkho',
            name='nhan_vien_nhap',
        ),
        migrations.RemoveField(
            model_name='phieuxuatkho',
            name='nhan_vien_xuat',
        ),
        migrations.RemoveField(
            model_name='yeucaunghiphep',
            name='nguoi_duyet',
        ),
        migrations.RemoveField(
            model_name='yeucaunghiphep',
            name='nhan_vien',
        ),
        migrations.DeleteModel(
            name='ChiTietNhapKho',
        ),
        migrations.DeleteModel(
            name='ChiTietXuatKho',
        ),
        migrations.DeleteModel(
            name='DanhMucSanPham',
        ),
        migrations.DeleteModel(
            name='SanPham',
        ),
        migrations.DeleteModel(
            name='PhieuNhapKho',
        ),
        migrations.DeleteModel(
            name='PhieuXuatKho',
        ),
        migrations.DeleteModel(
            name='YeuCauNghiPhep',
        ),
    ]
